# Site wide configuration
title: Unzensored
description: 'Exagerations and short words'
url: http://www.unzenso.red/
date_format: '%d %B %Y'
fort_awesome_icon: 'cog fa-spin'

# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name: Nur Álvarez González
    email: nur@unzenso.red
    github: nur-ag
    twitter: subnurmality
    linkedin: nuralvarez
    facebook:
    google_plus:
    youtube: 

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'unzensored'

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 5

# Markdown
highlighter: rouge

# Enable when using kramdown (you will need to use ~~~ instead of ```)
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# Gems
gems: ['jekyll-paginate']

# Exclude
exclude: ['README.md']

